// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: cloudsaveValidatorService.proto

package validator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TTLConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTLConfig) Reset() {
	*x = TTLConfig{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTLConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTLConfig) ProtoMessage() {}

func (x *TTLConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTLConfig.ProtoReflect.Descriptor instead.
func (*TTLConfig) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{0}
}

func (x *TTLConfig) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TTLConfig) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type GameRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	SetBy         string                 `protobuf:"bytes,4,opt,name=setBy,proto3" json:"setBy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	TtlConfig     *TTLConfig             `protobuf:"bytes,7,opt,name=ttlConfig,proto3,oneof" json:"ttlConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRecord) Reset() {
	*x = GameRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRecord) ProtoMessage() {}

func (x *GameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRecord.ProtoReflect.Descriptor instead.
func (*GameRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{1}
}

func (x *GameRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GameRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GameRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameRecord) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

func (x *GameRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GameRecord) GetTtlConfig() *TTLConfig {
	if x != nil {
		return x.TtlConfig
	}
	return nil
}

type BulkGameRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameRecords   []*GameRecord          `protobuf:"bytes,1,rep,name=gameRecords,proto3" json:"gameRecords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkGameRecord) Reset() {
	*x = BulkGameRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGameRecord) ProtoMessage() {}

func (x *BulkGameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGameRecord.ProtoReflect.Descriptor instead.
func (*BulkGameRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{2}
}

func (x *BulkGameRecord) GetGameRecords() []*GameRecord {
	if x != nil {
		return x.GameRecords
	}
	return nil
}

type PlayerRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	SetBy           string                 `protobuf:"bytes,4,opt,name=setBy,proto3" json:"setBy,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId          string                 `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	IsPublic        bool                   `protobuf:"varint,7,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	RequesterUserId *string                `protobuf:"bytes,9,opt,name=requesterUserId,proto3,oneof" json:"requesterUserId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerRecord) Reset() {
	*x = PlayerRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRecord) ProtoMessage() {}

func (x *PlayerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRecord.ProtoReflect.Descriptor instead.
func (*PlayerRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PlayerRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PlayerRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PlayerRecord) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

func (x *PlayerRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlayerRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerRecord) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *PlayerRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PlayerRecord) GetRequesterUserId() string {
	if x != nil && x.RequesterUserId != nil {
		return *x.RequesterUserId
	}
	return ""
}

type BulkPlayerRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerRecords []*PlayerRecord        `protobuf:"bytes,1,rep,name=playerRecords,proto3" json:"playerRecords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkPlayerRecord) Reset() {
	*x = BulkPlayerRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkPlayerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPlayerRecord) ProtoMessage() {}

func (x *BulkPlayerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPlayerRecord.ProtoReflect.Descriptor instead.
func (*BulkPlayerRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{4}
}

func (x *BulkPlayerRecord) GetPlayerRecords() []*PlayerRecord {
	if x != nil {
		return x.PlayerRecords
	}
	return nil
}

type AdminGameRecord struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Key       string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// payload is map of string object
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGameRecord) Reset() {
	*x = AdminGameRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGameRecord) ProtoMessage() {}

func (x *AdminGameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGameRecord.ProtoReflect.Descriptor instead.
func (*AdminGameRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{5}
}

func (x *AdminGameRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminGameRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AdminGameRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AdminGameRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminGameRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BulkAdminGameRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdminGameRecords []*AdminGameRecord     `protobuf:"bytes,1,rep,name=adminGameRecords,proto3" json:"adminGameRecords,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BulkAdminGameRecord) Reset() {
	*x = BulkAdminGameRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkAdminGameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkAdminGameRecord) ProtoMessage() {}

func (x *BulkAdminGameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkAdminGameRecord.ProtoReflect.Descriptor instead.
func (*BulkAdminGameRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{6}
}

func (x *BulkAdminGameRecord) GetAdminGameRecords() []*AdminGameRecord {
	if x != nil {
		return x.AdminGameRecords
	}
	return nil
}

type AdminPlayerRecord struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Key       string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// payload is map of string object
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPlayerRecord) Reset() {
	*x = AdminPlayerRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPlayerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPlayerRecord) ProtoMessage() {}

func (x *AdminPlayerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPlayerRecord.ProtoReflect.Descriptor instead.
func (*AdminPlayerRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{7}
}

func (x *AdminPlayerRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminPlayerRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AdminPlayerRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AdminPlayerRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminPlayerRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminPlayerRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BulkAdminPlayerRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AdminPlayerRecords []*AdminPlayerRecord   `protobuf:"bytes,1,rep,name=adminPlayerRecords,proto3" json:"adminPlayerRecords,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BulkAdminPlayerRecord) Reset() {
	*x = BulkAdminPlayerRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkAdminPlayerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkAdminPlayerRecord) ProtoMessage() {}

func (x *BulkAdminPlayerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkAdminPlayerRecord.ProtoReflect.Descriptor instead.
func (*BulkAdminPlayerRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{8}
}

func (x *BulkAdminPlayerRecord) GetAdminPlayerRecords() []*AdminPlayerRecord {
	if x != nil {
		return x.AdminPlayerRecords
	}
	return nil
}

type BinaryInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// url is an URL to get the binary record
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryInfo) Reset() {
	*x = BinaryInfo{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryInfo) ProtoMessage() {}

func (x *BinaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryInfo.ProtoReflect.Descriptor instead.
func (*BinaryInfo) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{9}
}

func (x *BinaryInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BinaryInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BinaryInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BinaryInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BinaryInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GameBinaryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	BinaryInfo    *BinaryInfo            `protobuf:"bytes,3,opt,name=binaryInfo,proto3,oneof" json:"binaryInfo,omitempty"`
	SetBy         string                 `protobuf:"bytes,4,opt,name=setBy,proto3" json:"setBy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	TtlConfig     *TTLConfig             `protobuf:"bytes,7,opt,name=ttlConfig,proto3,oneof" json:"ttlConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBinaryRecord) Reset() {
	*x = GameBinaryRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBinaryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBinaryRecord) ProtoMessage() {}

func (x *GameBinaryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBinaryRecord.ProtoReflect.Descriptor instead.
func (*GameBinaryRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{10}
}

func (x *GameBinaryRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GameBinaryRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GameBinaryRecord) GetBinaryInfo() *BinaryInfo {
	if x != nil {
		return x.BinaryInfo
	}
	return nil
}

func (x *GameBinaryRecord) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

func (x *GameBinaryRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameBinaryRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GameBinaryRecord) GetTtlConfig() *TTLConfig {
	if x != nil {
		return x.TtlConfig
	}
	return nil
}

type BulkGameBinaryRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GameBinaryRecords []*GameBinaryRecord    `protobuf:"bytes,1,rep,name=gameBinaryRecords,proto3" json:"gameBinaryRecords,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BulkGameBinaryRecord) Reset() {
	*x = BulkGameBinaryRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGameBinaryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGameBinaryRecord) ProtoMessage() {}

func (x *BulkGameBinaryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGameBinaryRecord.ProtoReflect.Descriptor instead.
func (*BulkGameBinaryRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{11}
}

func (x *BulkGameBinaryRecord) GetGameBinaryRecords() []*GameBinaryRecord {
	if x != nil {
		return x.GameBinaryRecords
	}
	return nil
}

type PlayerBinaryRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	BinaryInfo      *BinaryInfo            `protobuf:"bytes,3,opt,name=binaryInfo,proto3" json:"binaryInfo,omitempty"`
	SetBy           string                 `protobuf:"bytes,4,opt,name=setBy,proto3" json:"setBy,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId          string                 `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	IsPublic        bool                   `protobuf:"varint,7,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	RequesterUserId *string                `protobuf:"bytes,9,opt,name=requesterUserId,proto3,oneof" json:"requesterUserId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerBinaryRecord) Reset() {
	*x = PlayerBinaryRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBinaryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBinaryRecord) ProtoMessage() {}

func (x *PlayerBinaryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBinaryRecord.ProtoReflect.Descriptor instead.
func (*PlayerBinaryRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerBinaryRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PlayerBinaryRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PlayerBinaryRecord) GetBinaryInfo() *BinaryInfo {
	if x != nil {
		return x.BinaryInfo
	}
	return nil
}

func (x *PlayerBinaryRecord) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

func (x *PlayerBinaryRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlayerBinaryRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerBinaryRecord) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *PlayerBinaryRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PlayerBinaryRecord) GetRequesterUserId() string {
	if x != nil && x.RequesterUserId != nil {
		return *x.RequesterUserId
	}
	return ""
}

type BulkPlayerBinaryRecord struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerBinaryRecords []*PlayerBinaryRecord  `protobuf:"bytes,1,rep,name=playerBinaryRecords,proto3" json:"playerBinaryRecords,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BulkPlayerBinaryRecord) Reset() {
	*x = BulkPlayerBinaryRecord{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkPlayerBinaryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPlayerBinaryRecord) ProtoMessage() {}

func (x *BulkPlayerBinaryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPlayerBinaryRecord.ProtoReflect.Descriptor instead.
func (*BulkPlayerBinaryRecord) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{13}
}

func (x *BulkPlayerBinaryRecord) GetPlayerBinaryRecords() []*PlayerBinaryRecord {
	if x != nil {
		return x.PlayerBinaryRecords
	}
	return nil
}

type GameRecordValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRecordValidationResult) Reset() {
	*x = GameRecordValidationResult{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRecordValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRecordValidationResult) ProtoMessage() {}

func (x *GameRecordValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRecordValidationResult.ProtoReflect.Descriptor instead.
func (*GameRecordValidationResult) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{14}
}

func (x *GameRecordValidationResult) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *GameRecordValidationResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GameRecordValidationResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type BulkGameRecordValidationResult struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	ValidationResults []*GameRecordValidationResult `protobuf:"bytes,1,rep,name=validationResults,proto3" json:"validationResults,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BulkGameRecordValidationResult) Reset() {
	*x = BulkGameRecordValidationResult{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGameRecordValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGameRecordValidationResult) ProtoMessage() {}

func (x *BulkGameRecordValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGameRecordValidationResult.ProtoReflect.Descriptor instead.
func (*BulkGameRecordValidationResult) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{15}
}

func (x *BulkGameRecordValidationResult) GetValidationResults() []*GameRecordValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

type PlayerRecordValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRecordValidationResult) Reset() {
	*x = PlayerRecordValidationResult{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRecordValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRecordValidationResult) ProtoMessage() {}

func (x *PlayerRecordValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRecordValidationResult.ProtoReflect.Descriptor instead.
func (*PlayerRecordValidationResult) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerRecordValidationResult) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *PlayerRecordValidationResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PlayerRecordValidationResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerRecordValidationResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type BulkPlayerRecordValidationResult struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	ValidationResults []*PlayerRecordValidationResult `protobuf:"bytes,1,rep,name=validationResults,proto3" json:"validationResults,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BulkPlayerRecordValidationResult) Reset() {
	*x = BulkPlayerRecordValidationResult{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkPlayerRecordValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPlayerRecordValidationResult) ProtoMessage() {}

func (x *BulkPlayerRecordValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPlayerRecordValidationResult.ProtoReflect.Descriptor instead.
func (*BulkPlayerRecordValidationResult) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{17}
}

func (x *BulkPlayerRecordValidationResult) GetValidationResults() []*PlayerRecordValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_cloudsaveValidatorService_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_cloudsaveValidatorService_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_cloudsaveValidatorService_proto_rawDescGZIP(), []int{18}
}

func (x *Error) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Error) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_cloudsaveValidatorService_proto protoreflect.FileDescriptor

const file_cloudsaveValidatorService_proto_rawDesc = "" +
	"\n" +
	"\x1fcloudsaveValidatorService.proto\x12\x1daccelbyte.cloudsave.validator\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\tTTLConfig\x128\n" +
	"\texpiresAt\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xce\x02\n" +
	"\n" +
	"GameRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05setBy\x18\x04 \x01(\tR\x05setBy\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01\x12K\n" +
	"\tttlConfig\x18\a \x01(\v2(.accelbyte.cloudsave.validator.TTLConfigH\x01R\tttlConfig\x88\x01\x01B\f\n" +
	"\n" +
	"_updatedAtB\f\n" +
	"\n" +
	"_ttlConfig\"]\n" +
	"\x0eBulkGameRecord\x12K\n" +
	"\vgameRecords\x18\x01 \x03(\v2).accelbyte.cloudsave.validator.GameRecordR\vgameRecords\"\xec\x02\n" +
	"\fPlayerRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05setBy\x18\x04 \x01(\tR\x05setBy\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06userId\x18\x06 \x01(\tR\x06userId\x12\x1a\n" +
	"\bisPublic\x18\a \x01(\bR\bisPublic\x12=\n" +
	"\tupdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01\x12-\n" +
	"\x0frequesterUserId\x18\t \x01(\tH\x01R\x0frequesterUserId\x88\x01\x01B\f\n" +
	"\n" +
	"_updatedAtB\x12\n" +
	"\x10_requesterUserId\"e\n" +
	"\x10BulkPlayerRecord\x12Q\n" +
	"\rplayerRecords\x18\x01 \x03(\v2+.accelbyte.cloudsave.validator.PlayerRecordR\rplayerRecords\"\xe2\x01\n" +
	"\x0fAdminGameRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\tupdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_updatedAt\"q\n" +
	"\x13BulkAdminGameRecord\x12Z\n" +
	"\x10adminGameRecords\x18\x01 \x03(\v2..accelbyte.cloudsave.validator.AdminGameRecordR\x10adminGameRecords\"\xfc\x01\n" +
	"\x11AdminPlayerRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\tR\x06userId\x12=\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_updatedAt\"y\n" +
	"\x15BulkAdminPlayerRecord\x12`\n" +
	"\x12adminPlayerRecords\x18\x01 \x03(\v20.accelbyte.cloudsave.validator.AdminPlayerRecordR\x12adminPlayerRecords\"\xe1\x01\n" +
	"\n" +
	"BinaryInfo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12 \n" +
	"\vcontentType\x18\x03 \x01(\tR\vcontentType\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\tupdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_updatedAt\"\x99\x03\n" +
	"\x10GameBinaryRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12N\n" +
	"\n" +
	"binaryInfo\x18\x03 \x01(\v2).accelbyte.cloudsave.validator.BinaryInfoH\x00R\n" +
	"binaryInfo\x88\x01\x01\x12\x14\n" +
	"\x05setBy\x18\x04 \x01(\tR\x05setBy\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tupdatedAt\x88\x01\x01\x12K\n" +
	"\tttlConfig\x18\a \x01(\v2(.accelbyte.cloudsave.validator.TTLConfigH\x02R\tttlConfig\x88\x01\x01B\r\n" +
	"\v_binaryInfoB\f\n" +
	"\n" +
	"_updatedAtB\f\n" +
	"\n" +
	"_ttlConfig\"u\n" +
	"\x14BulkGameBinaryRecord\x12]\n" +
	"\x11gameBinaryRecords\x18\x01 \x03(\v2/.accelbyte.cloudsave.validator.GameBinaryRecordR\x11gameBinaryRecords\"\xa3\x03\n" +
	"\x12PlayerBinaryRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12I\n" +
	"\n" +
	"binaryInfo\x18\x03 \x01(\v2).accelbyte.cloudsave.validator.BinaryInfoR\n" +
	"binaryInfo\x12\x14\n" +
	"\x05setBy\x18\x04 \x01(\tR\x05setBy\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06userId\x18\x06 \x01(\tR\x06userId\x12\x1a\n" +
	"\bisPublic\x18\a \x01(\bR\bisPublic\x12=\n" +
	"\tupdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01\x12-\n" +
	"\x0frequesterUserId\x18\t \x01(\tH\x01R\x0frequesterUserId\x88\x01\x01B\f\n" +
	"\n" +
	"_updatedAtB\x12\n" +
	"\x10_requesterUserId\"}\n" +
	"\x16BulkPlayerBinaryRecord\x12c\n" +
	"\x13playerBinaryRecords\x18\x01 \x03(\v21.accelbyte.cloudsave.validator.PlayerBinaryRecordR\x13playerBinaryRecords\"\x97\x01\n" +
	"\x1aGameRecordValidationResult\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12?\n" +
	"\x05error\x18\x03 \x01(\v2$.accelbyte.cloudsave.validator.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x89\x01\n" +
	"\x1eBulkGameRecordValidationResult\x12g\n" +
	"\x11validationResults\x18\x01 \x03(\v29.accelbyte.cloudsave.validator.GameRecordValidationResultR\x11validationResults\"\xb1\x01\n" +
	"\x1cPlayerRecordValidationResult\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12?\n" +
	"\x05error\x18\x04 \x01(\v2$.accelbyte.cloudsave.validator.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x8d\x01\n" +
	" BulkPlayerRecordValidationResult\x12i\n" +
	"\x11validationResults\x18\x01 \x03(\v2;.accelbyte.cloudsave.validator.PlayerRecordValidationResultR\x11validationResults\"I\n" +
	"\x05Error\x12\x1c\n" +
	"\terrorCode\x18\x01 \x01(\x05R\terrorCode\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage2\xbf\x0f\n" +
	"\x19CloudsaveValidatorService\x12}\n" +
	"\x15BeforeWriteGameRecord\x12).accelbyte.cloudsave.validator.GameRecord\x1a9.accelbyte.cloudsave.validator.GameRecordValidationResult\x12{\n" +
	"\x13AfterReadGameRecord\x12).accelbyte.cloudsave.validator.GameRecord\x1a9.accelbyte.cloudsave.validator.GameRecordValidationResult\x12\x87\x01\n" +
	"\x17AfterBulkReadGameRecord\x12-.accelbyte.cloudsave.validator.BulkGameRecord\x1a=.accelbyte.cloudsave.validator.BulkGameRecordValidationResult\x12\x83\x01\n" +
	"\x17BeforeWritePlayerRecord\x12+.accelbyte.cloudsave.validator.PlayerRecord\x1a;.accelbyte.cloudsave.validator.PlayerRecordValidationResult\x12\x81\x01\n" +
	"\x15AfterReadPlayerRecord\x12+.accelbyte.cloudsave.validator.PlayerRecord\x1a;.accelbyte.cloudsave.validator.PlayerRecordValidationResult\x12\x8d\x01\n" +
	"\x19AfterBulkReadPlayerRecord\x12/.accelbyte.cloudsave.validator.BulkPlayerRecord\x1a?.accelbyte.cloudsave.validator.BulkPlayerRecordValidationResult\x12\x87\x01\n" +
	"\x1aBeforeWriteAdminGameRecord\x12..accelbyte.cloudsave.validator.AdminGameRecord\x1a9.accelbyte.cloudsave.validator.GameRecordValidationResult\x12\x8d\x01\n" +
	"\x1cBeforeWriteAdminPlayerRecord\x120.accelbyte.cloudsave.validator.AdminPlayerRecord\x1a;.accelbyte.cloudsave.validator.PlayerRecordValidationResult\x12\x89\x01\n" +
	"\x1bBeforeWriteGameBinaryRecord\x12/.accelbyte.cloudsave.validator.GameBinaryRecord\x1a9.accelbyte.cloudsave.validator.GameRecordValidationResult\x12\x87\x01\n" +
	"\x19AfterReadGameBinaryRecord\x12/.accelbyte.cloudsave.validator.GameBinaryRecord\x1a9.accelbyte.cloudsave.validator.GameRecordValidationResult\x12\x93\x01\n" +
	"\x1dAfterBulkReadGameBinaryRecord\x123.accelbyte.cloudsave.validator.BulkGameBinaryRecord\x1a=.accelbyte.cloudsave.validator.BulkGameRecordValidationResult\x12\x8f\x01\n" +
	"\x1dBeforeWritePlayerBinaryRecord\x121.accelbyte.cloudsave.validator.PlayerBinaryRecord\x1a;.accelbyte.cloudsave.validator.PlayerRecordValidationResult\x12\x8d\x01\n" +
	"\x1bAfterReadPlayerBinaryRecord\x121.accelbyte.cloudsave.validator.PlayerBinaryRecord\x1a;.accelbyte.cloudsave.validator.PlayerRecordValidationResult\x12\x99\x01\n" +
	"\x1fAfterBulkReadPlayerBinaryRecord\x125.accelbyte.cloudsave.validator.BulkPlayerBinaryRecord\x1a?.accelbyte.cloudsave.validator.BulkPlayerRecordValidationResultBh\n" +
	"!net.accelbyte.cloudsave.validatorP\x01Z!accelbyte.net/cloudsave/validator\xaa\x02\x1dAccelByte.Cloudsave.Validatorb\x06proto3"

var (
	file_cloudsaveValidatorService_proto_rawDescOnce sync.Once
	file_cloudsaveValidatorService_proto_rawDescData []byte
)

func file_cloudsaveValidatorService_proto_rawDescGZIP() []byte {
	file_cloudsaveValidatorService_proto_rawDescOnce.Do(func() {
		file_cloudsaveValidatorService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloudsaveValidatorService_proto_rawDesc), len(file_cloudsaveValidatorService_proto_rawDesc)))
	})
	return file_cloudsaveValidatorService_proto_rawDescData
}

var file_cloudsaveValidatorService_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cloudsaveValidatorService_proto_goTypes = []any{
	(*TTLConfig)(nil),                        // 0: accelbyte.cloudsave.validator.TTLConfig
	(*GameRecord)(nil),                       // 1: accelbyte.cloudsave.validator.GameRecord
	(*BulkGameRecord)(nil),                   // 2: accelbyte.cloudsave.validator.BulkGameRecord
	(*PlayerRecord)(nil),                     // 3: accelbyte.cloudsave.validator.PlayerRecord
	(*BulkPlayerRecord)(nil),                 // 4: accelbyte.cloudsave.validator.BulkPlayerRecord
	(*AdminGameRecord)(nil),                  // 5: accelbyte.cloudsave.validator.AdminGameRecord
	(*BulkAdminGameRecord)(nil),              // 6: accelbyte.cloudsave.validator.BulkAdminGameRecord
	(*AdminPlayerRecord)(nil),                // 7: accelbyte.cloudsave.validator.AdminPlayerRecord
	(*BulkAdminPlayerRecord)(nil),            // 8: accelbyte.cloudsave.validator.BulkAdminPlayerRecord
	(*BinaryInfo)(nil),                       // 9: accelbyte.cloudsave.validator.BinaryInfo
	(*GameBinaryRecord)(nil),                 // 10: accelbyte.cloudsave.validator.GameBinaryRecord
	(*BulkGameBinaryRecord)(nil),             // 11: accelbyte.cloudsave.validator.BulkGameBinaryRecord
	(*PlayerBinaryRecord)(nil),               // 12: accelbyte.cloudsave.validator.PlayerBinaryRecord
	(*BulkPlayerBinaryRecord)(nil),           // 13: accelbyte.cloudsave.validator.BulkPlayerBinaryRecord
	(*GameRecordValidationResult)(nil),       // 14: accelbyte.cloudsave.validator.GameRecordValidationResult
	(*BulkGameRecordValidationResult)(nil),   // 15: accelbyte.cloudsave.validator.BulkGameRecordValidationResult
	(*PlayerRecordValidationResult)(nil),     // 16: accelbyte.cloudsave.validator.PlayerRecordValidationResult
	(*BulkPlayerRecordValidationResult)(nil), // 17: accelbyte.cloudsave.validator.BulkPlayerRecordValidationResult
	(*Error)(nil),                            // 18: accelbyte.cloudsave.validator.Error
	(*timestamppb.Timestamp)(nil),            // 19: google.protobuf.Timestamp
}
var file_cloudsaveValidatorService_proto_depIdxs = []int32{
	19, // 0: accelbyte.cloudsave.validator.TTLConfig.expiresAt:type_name -> google.protobuf.Timestamp
	19, // 1: accelbyte.cloudsave.validator.GameRecord.createdAt:type_name -> google.protobuf.Timestamp
	19, // 2: accelbyte.cloudsave.validator.GameRecord.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: accelbyte.cloudsave.validator.GameRecord.ttlConfig:type_name -> accelbyte.cloudsave.validator.TTLConfig
	1,  // 4: accelbyte.cloudsave.validator.BulkGameRecord.gameRecords:type_name -> accelbyte.cloudsave.validator.GameRecord
	19, // 5: accelbyte.cloudsave.validator.PlayerRecord.createdAt:type_name -> google.protobuf.Timestamp
	19, // 6: accelbyte.cloudsave.validator.PlayerRecord.updatedAt:type_name -> google.protobuf.Timestamp
	3,  // 7: accelbyte.cloudsave.validator.BulkPlayerRecord.playerRecords:type_name -> accelbyte.cloudsave.validator.PlayerRecord
	19, // 8: accelbyte.cloudsave.validator.AdminGameRecord.createdAt:type_name -> google.protobuf.Timestamp
	19, // 9: accelbyte.cloudsave.validator.AdminGameRecord.updatedAt:type_name -> google.protobuf.Timestamp
	5,  // 10: accelbyte.cloudsave.validator.BulkAdminGameRecord.adminGameRecords:type_name -> accelbyte.cloudsave.validator.AdminGameRecord
	19, // 11: accelbyte.cloudsave.validator.AdminPlayerRecord.createdAt:type_name -> google.protobuf.Timestamp
	19, // 12: accelbyte.cloudsave.validator.AdminPlayerRecord.updatedAt:type_name -> google.protobuf.Timestamp
	7,  // 13: accelbyte.cloudsave.validator.BulkAdminPlayerRecord.adminPlayerRecords:type_name -> accelbyte.cloudsave.validator.AdminPlayerRecord
	19, // 14: accelbyte.cloudsave.validator.BinaryInfo.createdAt:type_name -> google.protobuf.Timestamp
	19, // 15: accelbyte.cloudsave.validator.BinaryInfo.updatedAt:type_name -> google.protobuf.Timestamp
	9,  // 16: accelbyte.cloudsave.validator.GameBinaryRecord.binaryInfo:type_name -> accelbyte.cloudsave.validator.BinaryInfo
	19, // 17: accelbyte.cloudsave.validator.GameBinaryRecord.createdAt:type_name -> google.protobuf.Timestamp
	19, // 18: accelbyte.cloudsave.validator.GameBinaryRecord.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 19: accelbyte.cloudsave.validator.GameBinaryRecord.ttlConfig:type_name -> accelbyte.cloudsave.validator.TTLConfig
	10, // 20: accelbyte.cloudsave.validator.BulkGameBinaryRecord.gameBinaryRecords:type_name -> accelbyte.cloudsave.validator.GameBinaryRecord
	9,  // 21: accelbyte.cloudsave.validator.PlayerBinaryRecord.binaryInfo:type_name -> accelbyte.cloudsave.validator.BinaryInfo
	19, // 22: accelbyte.cloudsave.validator.PlayerBinaryRecord.createdAt:type_name -> google.protobuf.Timestamp
	19, // 23: accelbyte.cloudsave.validator.PlayerBinaryRecord.updatedAt:type_name -> google.protobuf.Timestamp
	12, // 24: accelbyte.cloudsave.validator.BulkPlayerBinaryRecord.playerBinaryRecords:type_name -> accelbyte.cloudsave.validator.PlayerBinaryRecord
	18, // 25: accelbyte.cloudsave.validator.GameRecordValidationResult.error:type_name -> accelbyte.cloudsave.validator.Error
	14, // 26: accelbyte.cloudsave.validator.BulkGameRecordValidationResult.validationResults:type_name -> accelbyte.cloudsave.validator.GameRecordValidationResult
	18, // 27: accelbyte.cloudsave.validator.PlayerRecordValidationResult.error:type_name -> accelbyte.cloudsave.validator.Error
	16, // 28: accelbyte.cloudsave.validator.BulkPlayerRecordValidationResult.validationResults:type_name -> accelbyte.cloudsave.validator.PlayerRecordValidationResult
	1,  // 29: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteGameRecord:input_type -> accelbyte.cloudsave.validator.GameRecord
	1,  // 30: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadGameRecord:input_type -> accelbyte.cloudsave.validator.GameRecord
	2,  // 31: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadGameRecord:input_type -> accelbyte.cloudsave.validator.BulkGameRecord
	3,  // 32: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWritePlayerRecord:input_type -> accelbyte.cloudsave.validator.PlayerRecord
	3,  // 33: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadPlayerRecord:input_type -> accelbyte.cloudsave.validator.PlayerRecord
	4,  // 34: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadPlayerRecord:input_type -> accelbyte.cloudsave.validator.BulkPlayerRecord
	5,  // 35: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteAdminGameRecord:input_type -> accelbyte.cloudsave.validator.AdminGameRecord
	7,  // 36: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteAdminPlayerRecord:input_type -> accelbyte.cloudsave.validator.AdminPlayerRecord
	10, // 37: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteGameBinaryRecord:input_type -> accelbyte.cloudsave.validator.GameBinaryRecord
	10, // 38: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadGameBinaryRecord:input_type -> accelbyte.cloudsave.validator.GameBinaryRecord
	11, // 39: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadGameBinaryRecord:input_type -> accelbyte.cloudsave.validator.BulkGameBinaryRecord
	12, // 40: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWritePlayerBinaryRecord:input_type -> accelbyte.cloudsave.validator.PlayerBinaryRecord
	12, // 41: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadPlayerBinaryRecord:input_type -> accelbyte.cloudsave.validator.PlayerBinaryRecord
	13, // 42: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadPlayerBinaryRecord:input_type -> accelbyte.cloudsave.validator.BulkPlayerBinaryRecord
	14, // 43: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteGameRecord:output_type -> accelbyte.cloudsave.validator.GameRecordValidationResult
	14, // 44: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadGameRecord:output_type -> accelbyte.cloudsave.validator.GameRecordValidationResult
	15, // 45: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadGameRecord:output_type -> accelbyte.cloudsave.validator.BulkGameRecordValidationResult
	16, // 46: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWritePlayerRecord:output_type -> accelbyte.cloudsave.validator.PlayerRecordValidationResult
	16, // 47: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadPlayerRecord:output_type -> accelbyte.cloudsave.validator.PlayerRecordValidationResult
	17, // 48: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadPlayerRecord:output_type -> accelbyte.cloudsave.validator.BulkPlayerRecordValidationResult
	14, // 49: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteAdminGameRecord:output_type -> accelbyte.cloudsave.validator.GameRecordValidationResult
	16, // 50: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteAdminPlayerRecord:output_type -> accelbyte.cloudsave.validator.PlayerRecordValidationResult
	14, // 51: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWriteGameBinaryRecord:output_type -> accelbyte.cloudsave.validator.GameRecordValidationResult
	14, // 52: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadGameBinaryRecord:output_type -> accelbyte.cloudsave.validator.GameRecordValidationResult
	15, // 53: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadGameBinaryRecord:output_type -> accelbyte.cloudsave.validator.BulkGameRecordValidationResult
	16, // 54: accelbyte.cloudsave.validator.CloudsaveValidatorService.BeforeWritePlayerBinaryRecord:output_type -> accelbyte.cloudsave.validator.PlayerRecordValidationResult
	16, // 55: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterReadPlayerBinaryRecord:output_type -> accelbyte.cloudsave.validator.PlayerRecordValidationResult
	17, // 56: accelbyte.cloudsave.validator.CloudsaveValidatorService.AfterBulkReadPlayerBinaryRecord:output_type -> accelbyte.cloudsave.validator.BulkPlayerRecordValidationResult
	43, // [43:57] is the sub-list for method output_type
	29, // [29:43] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_cloudsaveValidatorService_proto_init() }
func file_cloudsaveValidatorService_proto_init() {
	if File_cloudsaveValidatorService_proto != nil {
		return
	}
	file_cloudsaveValidatorService_proto_msgTypes[1].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[3].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[5].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[7].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[9].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[10].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[12].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[14].OneofWrappers = []any{}
	file_cloudsaveValidatorService_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloudsaveValidatorService_proto_rawDesc), len(file_cloudsaveValidatorService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloudsaveValidatorService_proto_goTypes,
		DependencyIndexes: file_cloudsaveValidatorService_proto_depIdxs,
		MessageInfos:      file_cloudsaveValidatorService_proto_msgTypes,
	}.Build()
	File_cloudsaveValidatorService_proto = out.File
	file_cloudsaveValidatorService_proto_goTypes = nil
	file_cloudsaveValidatorService_proto_depIdxs = nil
}
